options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-docker.pkg.dev/$PROJECT_ID/gcr-images/patient-medical-history-app:$COMMIT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-docker.pkg.dev/$PROJECT_ID/gcr-images/patient-medical-history-app:$COMMIT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:380.0.0'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud run deploy patient-medical-history-app \
      --image=us-docker.pkg.dev/$PROJECT_ID/gcr-images/patient-medical-history-app:$COMMIT_SHA \
      --region=us-central1 \
      --platform=managed \
      --allow-unauthenticated \
      --set-secrets=GOOGLE_CLIENT_ID=google-client-id:latest \
      --service-account=patient-app-sa@patient-medical-history-app.iam.gserviceaccount.com \
      --verbosity=debug

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:380.0.0'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Waiting for deployment to stabilize..."
    sleep 60
    echo "Fetching container logs:"
    gcloud run logs read --service=patient-medical-history-app --region=us-central1 --limit=50

images:
- 'us-docker.pkg.dev/$PROJECT_ID/gcr-images/patient-medical-history-app:$COMMIT_SHA'