options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:380.0.0'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Current service account:"
    gcloud auth list
    echo "Project configurations:"
    gcloud config list

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:380.0.0'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "Listing Artifact Registry repositories:"
    gcloud artifacts repositories list --location=us
    echo "Describing gcr-images repository:"
    gcloud artifacts repositories describe gcr-images --location=us || echo "Failed to describe repository"

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/patient-medical-history-app:$COMMIT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/patient-medical-history-app:$COMMIT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:380.0.0'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'patient-medical-history-app'
  - '--image'
  - 'gcr.io/$PROJECT_ID/patient-medical-history-app:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-secrets'
  - 'GOOGLE_CLIENT_ID=google-client-id:latest'

images:
- 'gcr.io/$PROJECT_ID/patient-medical-history-app:$COMMIT_SHA'