# Logging configuration
options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Print Docker version
- name: 'gcr.io/cloud-builders/docker'
  args: ['version']

# List contents of the current directory
- name: 'ubuntu'
  args: ['ls', '-la']

# Print contents of Dockerfile
- name: 'ubuntu'
  args: ['cat', 'Dockerfile']

# Build the container image with verbose output
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--progress=plain', '-t', 'us-docker.pkg.dev/$PROJECT_ID/gcr-images/patient-medical-history-app:$COMMIT_SHA', '.']
  id: 'build'

# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-docker.pkg.dev/$PROJECT_ID/gcr-images/patient-medical-history-app:$COMMIT_SHA']
  id: 'push'

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'patient-medical-history-app'
  - '--image'
  - 'us-docker.pkg.dev/$PROJECT_ID/gcr-images/patient-medical-history-app:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-secrets'
  - 'GOOGLE_CLIENT_ID=google-client-id:latest'

images:
- 'us-docker.pkg.dev/$PROJECT_ID/gcr-images/patient-medical-history-app:$COMMIT_SHA'